import { Publisher } from './helpers/Publisher.js';
import { ListOfGroupsController } from './components/ListOfGroups/ListOfGroupsController.js';
// import { EditGroupController } from './components/EditGroup/EditGroupController.js';
import { MentorHiringController } from './components/MentorHiring/MentorHiringController.js';
import { StudentDetailsController } from './components/StudentDetails/StudentDetailsController.js';
import { ListOfStudentsController } from './components/ListOfStudents/ListOfStudentsController.js';
import { AuthorizationController } from './components/Authorization/AuthorizationController.js';
import { ListOfLessonsController } from './components/ListOfLessons/ListOfLessonsController.js';
import { StudyInfoController } from './components/StudyInfo/StudyInfoController.js';
import { DeleteGroupController } from './components/DeleteGroup/DeleteGroupController.js';
import { FireMentorController } from './components/FireMentor/FireMentorController.js';
import { StartGroupController } from './components/StartGroup/StartGroupController.js';
import { DetailsOfGroupController } from './components/DetailsOfGroup/DetailsOfGroupController.js';
import { StartALessonController } from './components/StartALesson/StartALessonController.js';
import { DeleteStudentController } from './components/DeleteStudent/DeleteStudentController.js';
import { ListOfCoursesController } from './components/ListOfCourses/ListOfCoursesController.js';
import { SidebarController } from './components/Sidebar/SidebarController.js';
import { EditCourseController } from './components/EditCourse/EditCourseController.js';
import { RemoveCourseController } from './components/RemoveCourse/RemoveCourseController.js';
import { AddCourseController } from './components/AddCourse/AddCourseController.js';
import { HeaderController } from './components/Header/HeaderController.js';
import { EditLessonController } from './components/EditLesson/EditLessonController.js';
import { EditStudentController } from './components/EditStudent/EditStudentController.js';

const publisher = new Publisher();

// const editGroupController = new EditGroupController(publisher.methods);
const mentorHiringController = new MentorHiringController(publisher.methods);
const studentDetailsController = new StudentDetailsController(publisher.methods);
const listOfStudents = new ListOfStudentsController(publisher.methods);
const listOfLessonsController = new ListOfLessonsController(publisher.methods);
const studyInfoController = new StudyInfoController(publisher.methods);
const deleteGroupController = new DeleteGroupController(publisher.methods);
const fireMentorController = new FireMentorController(publisher.methods);
const startGroupController = new StartGroupController(publisher.methods);
const detailsOfGroupController = new DetailsOfGroupController(publisher.methods);
const startALessonContorller = new StartALessonController(publisher.methods);
const deleteStudentController = new DeleteStudentController(publisher.methods);
const removeCourseController = new RemoveCourseController(publisher.methods);
const listOfCoursesController = new ListOfCoursesController(publisher.methods);
const listOfGroupsController = new ListOfGroupsController(publisher.methods);
const addCourseController = new AddCourseController(publisher.methods);
const sidebar = new SidebarController(publisher.methods);
const editCourseController = new EditCourseController(publisher.methods);
const authorizationController = new AuthorizationController(publisher.methods);
const header = new HeaderController(publisher.methods);
const editLessonController = new EditLessonController(publisher.methods);
const editStudentController = new EditStudentController(publisher.methods);
